---

# This file is distributed under the Apache License (the
# "License"); you may not use this file except in compliance
# with the License.  See the LICENSE file distributed with
# this work for additional information regarding copyright
# ownership.
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# This file is derived from recipe.sh in OpenHPC distribution
# and ported by Linaro Ltd. and Fujitsu Ltd.

#
#roles/mrsh/tasks/main.yml
#

- block:
#if [[ ${enable_mrsh} -eq 1 ]];then
#     # Install mrsh
#     yum -y install mrsh-ohpc mrsh-rsh-compat-ohpc
  - name: Install mrsh-ohpc mrsh-rsh-compat-ohpc on master
    yum:
      state: latest
      name:
        - mrsh-ohpc
        - mrsh-rsh-compat-ohpc
    when:
      - inventory_hostname in groups[nt_sms]

  - name: Install mrsh-ohpc mrsh-rsh-compat-ohpc mrsh-server-ohpc on a computing node
    yum:
      state: latest
      name:
        - mrsh-ohpc
        - mrsh-rsh-compat-ohpc
        - mrsh-server-ohpc
    when:
      - inventory_hostname in groups[nt_cnodes]
      - enable_warewulf == false

#     echo "mshell          21212/tcp                  # mrshd" >> /etc/services
  - name: Identify mshell in services file on sms and a computing node and a development node
    lineinfile:
      path: /etc/services
      state: present
      backrefs: no
      regexp: '^mshell          21212/tcp                 # mrshd$'
      line: "mshell          21212/tcp                 # mrshd"
    when:
      ( inventory_hostname in groups[nt_sms] ) or
      ( inventory_hostname in groups[nt_devnodes] ) or
      ( ( inventory_hostname in groups[nt_cnodes] ) and ( enable_warewulf == false ) )

#     echo "mlogin            541/tcp                  # mrlogind" >> /etc/services
  - name: Identify mlogin in services file on sms and a computing node and a development node
    lineinfile:
      path: /etc/services
      state: present
      backrefs: no
      regexp: '^mlogin            541/tcp                 # mrlogind$'
      line: "mlogin            541/tcp                 # mrlogind"
    when:
      ( inventory_hostname in groups[nt_sms] ) or
      ( inventory_hostname in groups[nt_devnodes] ) or
      ( ( inventory_hostname in groups[nt_cnodes] ) and ( enable_warewulf == false ) )

  - name: Enable xinetd for computing on a computing node
    command: systemctl enable xinetd
    register: result
    failed_when: result.rc not in [0]
    when:
      - inventory_hostname in groups[nt_cnodes]
      - enable_warewulf == false

  when:
    - enable_mrsh == true
#fi

